# Generated by Django 4.2 on 2025-08-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('birth_year', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'Библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('desscription', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('published_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год Публикаций')),
                ('genre', models.CharField(blank=True, max_length=155, null=True, verbose_name='Жанр')),
                ('pages', models.CharField(blank=True, max_length=155, null=True, verbose_name='Кол-во Страниц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновленр')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='settings.author')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
